sftp:
  list:
    -
      serverName: C3
      host: 127.0.0.1
      port: 22
      username: user
      password: +kEy9ES87qLCT0ZHKYFnow==
      remotePath: '*'
      localPath: C://filepath/
      sessionTimeout: 15000
      channelTimeout: 150000
    -
      serverName: C4
      host: 127.0.0.1
      port: 22
      username: user
      password: +kEy9ES87qLCT0ZHKYFnow==
      remotePath: '*'
      localPath: C://filepath/
      sessionTimeout: 15000
      channelTimeout: 150000